version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '19:00'
      timezone: 'America/New_York'
    target-branch: 'develop'
    ignore:
      - dependency-name: 'typescript'
      - dependency-name: '*'
        update-types: 
          - 'version-update:semver-major'
    
