enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  cbnsndwch:
    npmAuthToken: "${CBNSNDWCH_NPM_TOKEN}"
    npmAlwaysAuth: true
    npmPublishRegistry: "https://registry.npmjs.org"
    
yarnPath: .yarn/releases/yarn-4.0.2.cjs
